# Generated by Django 6.0.2 on 2026-02-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_ledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
